version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
        - '*'
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
        - '*'
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      maven:
        patterns:
        - '*'
  - package-ecosystem: "npm"
    directory: "/services/web/viewer"
    schedule:
      interval: "daily"
    groups:
      npm:
        patterns:
        - '*'
  - package-ecosystem: "composer"
    directory: "/coins/cache-warmer/harvester"
    schedule:
      interval: "daily"
    groups:
      composer:
        patterns:
        - '*' 