apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
{{- if .Values.storage.class }}
  storageClassName: {{ .Values.storage.class }}
{{- end }}
  resources:
    requests:
      storage: 40Gi
