apiVersion: v1
data:
  rules.yml: |
    resourceRepository:
      resolved:
        patterns:
          - pattern: ^(gdz:.*:\d{8})$
            substitutions:
              - 'https://images.sub.uni-goettingen.de/iiif/image/$1/full/full/0/default.jpg'
              - 'https://manifests.sub.uni-goettingen.de/iiif/presentation/$1/manifest?version=r3rpa'
          - pattern: ^(record_.*.jpg)$
            substitutions:
              - 'https://sammlungen.uni-goettingen.de/api/v1/records/$1/full/full/0/default.jpg'
              - 'https://sammlungen.uni-goettingen.de/api/v1/records/$1/manifest/'
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  name: {{ .Release.Name }}-rules-yml
