apiVersion: v1
data:
  application.yml: |
    custom:
      iiif:
        identifier:
          escape: false

      image:
        quality:
          noop:
            enabled: false
          background:
            enabled: true
          fold:
            enabled: true
          stack:
            enabled: true
            name: nofold+transparentbg
            plugins: nofold,transparent-background

    plugins:
      packages: de.christianmahnke.lab.iiif.hymir

    management:
      endpoint:
        health:
          show-details: always
      endpoints:
        web:
          base-path: '/monitoring'
          exposure:
            include: '*'

    server:
      error:
        include-exception: true
        include-stacktrace: always

    spring:
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher
      profiles:
        active: local
        include: webjars, plugins

    ---
    spring:
      config:
        activate:
          on-profile: debug

    logging:
      level:
        ROOT: DEBUG
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  name: {{ .Release.Name }}-application-yaml
