apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: iiif-image-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iiif-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: iiif-proxy
    spec:
      containers:
        - name: iiif-image-server
          image: ghcr.io/cmahnke/iiif-proxy/iiif-image-server:main
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-env-configmap
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /opt/iiif-server/application.yml
              name: {{ .Release.Name }}-application-yaml
              readOnly: true
              subPath: application.yml
            - mountPath: /etc/iiif-server/rules.yml
              name: {{ .Release.Name }}-rules-yml
              readOnly: true
              subPath: rules.yml
            - mountPath: /etc/iiif-server/logback-spring.xml
              name: {{ .Release.Name }}-logback-spring-xml
              readOnly: true
              subPath: logback-spring.xml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: application.yml
                path: application.yml
            name: {{ .Release.Name }}-application-yaml
          name: {{ .Release.Name }}-application-yaml
        - configMap:
            items:
              - key: rules.yml
                path: rules.yml
            name: {{ .Release.Name }}-rules-yml
          name: {{ .Release.Name }}-rules-yml
        - configMap:
            items:
              - key: logback-spring.xml
                path: logback-spring.xml
            name: {{ .Release.Name }}-logback-spring-xml
          name: {{ .Release.Name }}-logback-spring-xml
status: {}
