{{- if ge (int .Capabilities.KubeVersion.Minor) 19 }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: iiif-proxy-ingress
spec:
  rules:
  - host: {{ .Values.web.frontendURL }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
{{- if ge (int .Capabilities.KubeVersion.Minor) 19 }}
          service:
            name: web
            port:
              number: 80
{{- else }}
          serviceName: web
          servicePort: http
{{- end }}
