apiVersion: v1
data:
  iiif_default_passthru.conf: |
    location ~ /image/v2/record_.*?/default.[a-z]\{3\}$ {
        proxy_set_header        Host sammlungen.uni-goettingen.de;
        proxy_ssl_name          sammlungen.uni-goettingen.de;
        include proxy_params;
        proxy_pass https://sammlungen.uni-goettingen.de;
        proxy_ssl_trusted_certificate /etc/nginx/ssl/backends/sammlungen.uni-goettingen.de.crt;
    }

    location ~ /image/v2/gdz:.*?/default.[a-z]\{3\}$ {
        include proxy_params;
        proxy_set_header        Host images.sub.uni-goettingen.de;
        proxy_ssl_name          images.sub.uni-goettingen.de;
        proxy_pass https://images.sub.uni-goettingen.de;
        proxy_ssl_trusted_certificate /etc/nginx/ssl/backends/images.sub.uni-goettingen.de.crt;
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  name: {{ .Release.Name }}-iiif-default-passthru
