apiVersion: v1
data:
  proxy_params: |
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto https;
    proxy_ssl_verify        off;
    proxy_ssl_server_name   on;
    proxy_ssl_session_reuse off;
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  name: {{ .Release.Name }}-web-proxy-params
