apiVersion: v1
data:
  proxy_cache.conf: |
    proxy_cache_path /data/nginx/cache keys_zone=default:10m inactive=60m max_size=256m;
    proxy_cache_methods GET HEAD POST;
    proxy_cache_valid 200 302  7d;
    proxy_cache_valid 404      1m;
    proxy_cache_valid 500      30s;
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  name: {{ .Release.Name }}-proxy-cache-conf
