apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: web

spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
      nodePort: 80
    - name: "8443"
      port: 8443
      targetPort: 443
      nodePort: 443
status:
  loadBalancer: {}
