#https://www.kenom.de/oai/?verb=ListRecords&metadataPrefix=lido&set=institution:DE-MUS-062622
oai_url: https://www.kenom.de/oai/
metadata_prefix: lido
set: institution:DE-MUS-062622
target_dir: ../../data/
