name: IIIF Web Server GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build_iiif-proxy-web:
    name: Push to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.4.0
        with:
          submodules: true
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: |
            ghcr.io/${{ github.repository }}/web
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: ./deployment/docker/web/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
