name: IIIF Image Server GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build_iiif-proxy-iiif-image-server:
    name: Push to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: |
            ghcr.io/${{ github.repository }}/iiif-image-server
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./deployment/docker/iiif-image-server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
